version: '3.7'
services:
    redis:
        image: redis
        ports:
            - 6379
    frontend:
        build: ./frontend
        ports:
            - "80:80"
    backend:
        build: ./backend
        ports:
            - "8080:8080"
    mysql:
        image: mysql
        ports:
            - 3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./docker/mysql:/var/lib/mysql
