version: '3.7'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app/backend
            - /app/backend/vendor
        depends_on:
            - mysql
        networks:
            - app
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app/frontend
            - /app/frontend/node_modules
            - /app/frontend/.next
        depends_on:
            - backend
        networks:
            - app
    redis:
        image: redis:alpine
        ports: 
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - ./redis:/app/redis
        networks:
            - app
    mysql:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - app

networks:
    app:
        driver: bridge
